# Generated by Django 3.1.2 on 2020-10-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SecretHitler.game'),
        ),
    ]
