# Generated by Django 3.1.2 on 2020-10-19 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0003_auto_20201019_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('voted', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_state',
            field=models.CharField(default='pre_game', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='elected_policies',
            field=models.CharField(default='[]', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='remaining_policies',
            field=models.CharField(default='[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='turn_no',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SecretHitler.game'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_chancellor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='SecretHitler.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_president',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='SecretHitler.player'),
        ),
    ]
