# Generated by Django 3.1.2 on 2020-10-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0004_auto_20201019_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='voted',
            field=models.BooleanField(default=True),
        ),
    ]
