# Generated by Django 3.1.2 on 2020-10-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0005_auto_20201019_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_president',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='SecretHitler.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='SecretHitler.game'),
        ),
        migrations.AlterField(
            model_name='player',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
