# Generated by Django 3.1.2 on 2020-10-19 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0006_auto_20201019_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_chancellor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roli', to='SecretHitler.player'),
        ),
    ]
