# Generated by Django 3.1.2 on 2020-10-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0008_auto_20201019_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_chancellor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chancellor', to='SecretHitler.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_president',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='SecretHitler.player'),
        ),
    ]
