# Generated by Django 3.1.2 on 2020-10-19 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0009_auto_20201019_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_chancellor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_chancellor_from', to='SecretHitler.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_president',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_president_from', to='SecretHitler.player'),
        ),
    ]
