# Generated by Django 3.1.2 on 2020-10-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecretHitler', '0010_auto_20201019_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='codeword',
            new_name='slug',
        ),
    ]
