"""empty message

Revision ID: 26d923da2993
Revises: add8b619d253
Create Date: 2020-11-17 13:45:17.484282

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '26d923da2993'
down_revision = 'add8b619d253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('_current_chancellor_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('_current_president_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('_last_chancellor_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('_last_president_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['_current_chancellor_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'game', 'player', ['_last_president_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'game', 'player', ['_last_chancellor_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'game', 'player', ['_current_president_id'], ['id'], use_alter=True)
    op.drop_column('game', 'last_chancellor_id')
    op.drop_column('game', 'current_chancellor_id')
    op.drop_column('game', 'current_president_id')
    op.drop_column('game', 'last_president_id')
    op.add_column('player', sa.Column('_game_slug', sa.String(length=64), nullable=True))
    op.alter_column('player', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_unique_constraint(None, 'player', ['sid'])
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'game', ['_game_slug'], ['slug'])
    op.drop_column('player', 'game_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('game_slug', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'game', ['game_slug'], ['slug'])
    op.drop_constraint(None, 'player', type_='unique')
    op.alter_column('player', 'name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('player', '_game_slug')
    op.add_column('game', sa.Column('last_president_id', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('current_president_id', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('current_chancellor_id', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('last_chancellor_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['last_chancellor_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['current_president_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['last_president_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['current_chancellor_id'], ['id'])
    op.drop_column('game', '_last_president_id')
    op.drop_column('game', '_last_chancellor_id')
    op.drop_column('game', '_current_president_id')
    op.drop_column('game', '_current_chancellor_id')
    # ### end Alembic commands ###
