"""empty message

Revision ID: 2fb6f84ddccb
Revises: e477ffe7c90d
Create Date: 2020-10-23 17:10:55.395557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb6f84ddccb'
down_revision = 'e477ffe7c90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_id', table_name='game')
    op.drop_index('ix_player_id', table_name='player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_player_id', 'player', ['id'], unique=1)
    op.create_index('ix_game_id', 'game', ['id'], unique=1)
    # ### end Alembic commands ###
