"""empty message

Revision ID: 31d61b16af37
Revises: 2432ca4617dd
Create Date: 2020-10-24 15:30:05.515615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d61b16af37'
down_revision = '2432ca4617dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_column('player', 'game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('game', sa.VARCHAR(length=64), nullable=True))
    op.create_foreign_key(None, 'player', 'game', ['game'], ['slug'])
    # ### end Alembic commands ###
