"""empty message

Revision ID: 329cfeaa6572
Revises: 7e1d3d1c5600
Create Date: 2020-11-18 14:55:06.749909

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '329cfeaa6572'
down_revision = '7e1d3d1c5600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('last_active', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'last_active')
    # ### end Alembic commands ###
