"""empty message

Revision ID: 37b775812c84
Revises: c8cc5f003caf
Create Date: 2020-11-02 20:24:34.881125

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37b775812c84'
down_revision = 'c8cc5f003caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('role', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'role')
    # ### end Alembic commands ###
