"""empty message

Revision ID: 449d99bcc2f4
Revises: 37b775812c84
Create Date: 2020-11-03 13:48:33.186533

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '449d99bcc2f4'
down_revision = '37b775812c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('_Player__role', sa.String(length=16), nullable=True))
    op.drop_column('player', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('role', sa.VARCHAR(length=16), nullable=True))
    op.drop_column('player', '_Player__role')
    # ### end Alembic commands ###
