"""empty message

Revision ID: 464376e64e22
Revises: fbcda437f380
Create Date: 2020-11-12 16:24:12.002717

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '464376e64e22'
down_revision = 'fbcda437f380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.add_column('game', sa.Column('current_chancellor_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('current_president_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('last_chancellor_id', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('last_president_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['last_president_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['last_chancellor_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['current_president_id'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['current_chancellor_id'], ['id'])
    op.drop_column('game', 'settings')
    op.drop_column('game', 'last_chancellor')
    op.drop_column('game', 'current_chancellor')
    op.drop_column('game', 'current_president')
    op.drop_column('game', 'last_president')
    op.add_column('player', sa.Column('current_game_slug', sa.String(length=64), nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'game', ['current_game_slug'], ['slug'])
    op.drop_column('player', 'game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('game', sa.VARCHAR(length=64), nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'game', ['game'], ['slug'])
    op.drop_column('player', 'current_game_slug')
    op.add_column('game', sa.Column('last_president', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('current_president', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('current_chancellor', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('last_chancellor', sa.INTEGER(), nullable=True))
    op.add_column('game', sa.Column('settings', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'player', ['current_chancellor'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['last_chancellor'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['current_president'], ['id'])
    op.create_foreign_key(None, 'game', 'player', ['last_president'], ['id'])
    op.create_foreign_key(None, 'game', 'settings', ['settings'], ['id'])
    op.drop_column('game', 'last_president_id')
    op.drop_column('game', 'last_chancellor_id')
    op.drop_column('game', 'current_president_id')
    op.drop_column('game', 'current_chancellor_id')
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
