"""empty message

Revision ID: 608a5865a44c
Revises: 
Create Date: 2020-10-30 15:49:22.241004

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '608a5865a44c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('current_president', sa.Integer(), nullable=True),
    sa.Column('current_chancellor', sa.Integer(), nullable=True),
    sa.Column('last_president', sa.Integer(), nullable=True),
    sa.Column('last_chancellor', sa.Integer(), nullable=True),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=16), nullable=False),
    sa.Column('elected_policies', sa.PickleType(), nullable=False),
    sa.Column('_Game__remaining_policies', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['current_chancellor'], ['player.id'], ),
    sa.ForeignKeyConstraint(['current_president'], ['player.id'], ),
    sa.ForeignKeyConstraint(['last_chancellor'], ['player.id'], ),
    sa.ForeignKeyConstraint(['last_president'], ['player.id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_game_slug'), 'game', ['slug'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('game', sa.String(length=64), nullable=True),
    sa.Column('_Player__voted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['game'], ['game.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_slug'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
