"""empty message

Revision ID: 7e1d3d1c5600
Revises: 
Create Date: 2020-11-17 21:31:51.099808

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7e1d3d1c5600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=16), nullable=False),
    sa.Column('elected_policies', sa.PickleType(), nullable=False),
    sa.Column('_Game__remaining_policies', sa.PickleType(), nullable=False),
    sa.Column('_current_president_id', sa.Integer(), nullable=True),
    sa.Column('_current_chancellor_id', sa.Integer(), nullable=True),
    sa.Column('_last_president_id', sa.Integer(), nullable=True),
    sa.Column('_last_chancellor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_current_chancellor_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['_current_president_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['_last_chancellor_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['_last_president_id'], ['player.id'], use_alter=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_game_slug'), 'game', ['slug'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('_Player__role', sa.String(length=16), nullable=True),
    sa.Column('_Player__voted', sa.Boolean(), nullable=True),
    sa.Column('_game_slug', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['_game_slug'], ['game.slug'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sid')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_slug'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
