"""empty message

Revision ID: add8b619d253
Revises: 
Create Date: 2020-11-14 13:47:48.283863

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'add8b619d253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('turn_no', sa.Integer(), nullable=False),
    sa.Column('current_state', sa.String(length=16), nullable=False),
    sa.Column('elected_policies', sa.PickleType(), nullable=False),
    sa.Column('_Game__remaining_policies', sa.PickleType(), nullable=False),
    sa.Column('current_president_id', sa.Integer(), nullable=True),
    sa.Column('current_chancellor_id', sa.Integer(), nullable=True),
    sa.Column('last_president_id', sa.Integer(), nullable=True),
    sa.Column('last_chancellor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_chancellor_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['current_president_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['last_chancellor_id'], ['player.id'], use_alter=True),
    sa.ForeignKeyConstraint(['last_president_id'], ['player.id'], use_alter=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_game_slug'), 'game', ['slug'], unique=True)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_Player__role', sa.String(length=16), nullable=True),
    sa.Column('_Player__voted', sa.Boolean(), nullable=True),
    sa.Column('game_slug', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['game_slug'], ['game.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_game_slug'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
