"""empty message

Revision ID: c8cc5f003caf
Revises: 608a5865a44c
Create Date: 2020-10-30 17:05:45.570263

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c8cc5f003caf'
down_revision = '608a5865a44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('sid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'sid')
    # ### end Alembic commands ###
